main/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    #ContactListView,
    ContactDetailView,
    ContactCreateView,
    ContactUpdateView,
    ContactDeleteView
)

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/<int:pk>/', ContactDetailView.as_view(), name='contact-detail'),
    path('contact/new/', ContactCreateView.as_view(), name='contact-create'),
    path('contact/<int:pk>/update/', ContactUpdateView.as_view(), name='contact-update'),
    path('contact/<int:pk>/delete/', ContactDeleteView.as_view(), name='contact-delete'),
    path('table', views.table, name='contact-table'),
    path('testmail', views.test_mail, name='testmail'),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nirmaan_csr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('main.urls', namespace='main')),
]

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from sendgrid.helpers.mail.to_email import To

class Contact(models.Model):
    company = models.CharField(max_length=200)
    person = models.CharField(max_length=100)
    desc = models.TextField()
    email = models.EmailField()
    number = models.CharField(max_length=15)
    status = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.company
    
    def get_absolute_url(self):
        return reverse('main:contact-detail', kwargs={'pk': self.pk})

    def save(self,*args,**kwargs):
        try:
            old = Contact.objects.get(pk = self.pk)
            if old:
                if old.status!=self.status:
                    old_status = old.status
                    new_status = self.status
                    company = self.company
                    to = self.author.email
                    message = Mail(
                    from_email='samriddhasinha@gmail.com',
                    to_emails = To(to),
                    subject='Nirmaan CSR | Status Update',
                    html_content='Status of contact '+company+' has been changed from <b>'+old_status+'</b> to <b>'+new_status+'</b>')
                    try:
                        sg = SendGridAPIClient('secret')
                        response = sg.send(message)
                        print(response.status_code)
                        print(response.body)
                        print(response.headers)
                        
                    except Exception as e:
                        print(e)
        except Exception as e:
            print(e)
                    
        super(Contact,self).save(*args,**kwargs)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
  
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.TextInput()
    last_name = forms.TextInput()

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

main/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Contact
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail


# Create your views here.
def index (request):
    return render(request, 'main/index.html')

def test_mail (request):
    message = Mail(
    from_email='f20200021@pilani.bits-pilani.ac.in',
    to_emails='samriddha@gmail.com',
    subject='Campus Reopening',
    html_content='<strong>lmao fr?</strong>')
    try:
        sg = SendGridAPIClient('secret')
        response = sg.send(message)
        print(response.status_code)
        print(response.body)
        print(response.headers)
        return HttpResponse("Success")
    except Exception as e:
        print(e)
        return HttpResponse("Fail")
    

def table (request):
    contacts = Contact.objects.all()
    return render(request, 'main/table.html', {'contacts' : contacts})

class ContactDetailView(DetailView):
    model = Contact


class ContactCreateView(LoginRequiredMixin, CreateView):
    model = Contact
    fields = ['company', 'person', 'desc', 'email', 'number', 'status']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ContactUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Contact
    fields = ['company', 'person', 'email', 'number', 'status']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        contact = self.get_object()
        if self.request.user == contact.author:
            return True
        return False


class ContactDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Contact
    success_url = '/'

    def test_func(self):
        contact = self.get_object()
        if self.request.user == contact.author:
            return True
        return False

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            # username = form.cleaned_data.get('username')
            # messages.success(request, f'Account created for {username}!')
            return redirect('main:index')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

main/templates/main/base.html
{% load static %}

<!DOCTYPE HTML>
<!--
	TXT by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Nirmaan Database</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href=" {% static 'assets/css/main.css' %} " />
	</head>
	<body class="is-preload">
		<div id="page-wrapper">

			
				<header id="header">
					<div class="logo container">
						<div>
							<h1><a href=" {% static 'index.html' %} " id="logo">Nirmaan</a></h1>
							<p>Towards a Better Future</p>
						</div>
					</div>
				</header>

			
				<nav id="nav">
					<ul>
						<li class="current"><a href="/">Home</a></li>
						{% if user.is_authenticated %}
							<li>
								<a href="#">Contacts</a>
								<ul>
									<li><a href="{% url 'main:contact-table' %}">View All</a></li>
									<li><a href="{% url 'main:contact-create' %}">Create New</a></li>
									
								</ul>
							</li>
						{% endif %}
						
						{% if user.is_authenticated %}
							<li><a href=" {% url 'logout' %} ">Logout</a></li>
						{% else %}
							<li><a href=" {% url 'login' %} ">Login</a></li>
						{% endif %}
					</ul>
				</nav>

			
				<section id="main">
					<div class="container">
						<div class="row">
							<div class="col-12">
								<div class="content">
									
									{% block content %}{% endblock %}

								</div>

							</div>
						</div>
					</div>
				</section>
				<footer id="footer">
					<div class="container">
						<div class="row gtr-200">
							<div id="copyright">
								<ul class="menu">
									<li>Made with &hearts; by Nirmaan PRD</li>
								</ul>
							</div>
						</div>
					</div>
				</footer>

					
				

		</div>

		<!-- Scripts -->
			<script src=" {% static 'assets/js/jquery.min.js' %} "></script>
			<script src=" {% static 'assets/js/jquery.dropotron.min.js' %} "></script>
			<script src=" {% static 'assets/js/jquery.scrolly.min.js' %} "></script>
			<script src=" {% static 'assets/js/browser.min.js' %} "></script>
			<script src=" {% static 'assets/js/breakpoints.min.js' %} "></script>
			<script src=" {% static 'assets/js/util.js' %} "></script>
			<script src=" {% static 'assets/js/main.js' %} "></script>
		{% block js %}
		{% endblock js %}
	</body>
</html>

main/templates/main/contact_confirm_delete.html
{% extends "main/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Contact</legend>
                <h2>Are you sure you want to delete the contact of "{{ object.company }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'main:contact-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

main/templates/main/contact_detail.html
{% extends "main/base.html" %}
{% block content %}
  <article class="media content-section">
    <!-- <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}"> -->
    <div class="media-body">
      <div class="article-metadata">
        <!-- <a class="mr-2" href="#">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small> -->
        
      </div>
      <h2 class="article-title">{{ object.company }}</h2>
      <p class="article-content">{{ object.person }}</p>
      <p class="article-content">{{ object.desc }}</p>
      <p class="article-content">{{ object.email }}</p>
      <p class="article-content">{{ object.number }}</p>
      <p class="article-content">{{ object.status }}</p>

      {% if object.author == user %}
            <div>
            <!-- <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'main:contact-update' object.id %}">Update</a> -->
            <button onclick="location.href='{% url 'main:contact-update' object.id %}'" type="button">Update</button>
            <!-- <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'main:contact-delete' object.id %}">Delete</a> -->
            <button class="button alt" onclick="location.href='{% url 'main:contact-delete' object.id %}'" type="button">Delete</button>
            </div>
      {% endif %}
    </div>
  </article>
{% endblock content %}

main/templates/main/contact_form.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">CSR Contact</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

main/templates/main/index - Copy.html
{% load static %}

<!DOCTYPE HTML>
<!--
	TXT by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Nirmaan CSR</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href=" {% static 'assets/css/main.css' %} " />
	</head>
	<body class="homepage is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header">
					<div class="logo container">
						<div>
							<h1><a href="/" id="logo">Nirmaan CSR</a></h1>
							<p>Towards a Better Future</p>
						</div>
					</div>
				</header>

			<!-- Nav -->
				<nav id="nav">
					<ul>
						<li class="current"><a href="/">Home</a></li>
						{% if user.is_authenticated %}
							<li>
								<a href="#">Contacts</a>
								<ul>
									<li><a href="{% url 'main:contact-table' %}">View All</a></li>
									<li><a href="{% url 'main:contact-create' %}">Create New</a></li>
									
								</ul>
							</li>
						{% endif %}
						<!-- <li><a href=" {% static 'left-sidebar.html' %} ">Left Sidebar</a></li>
						<li><a href=" {% static 'right-sidebar.html' %} ">Right Sidebar</a></li> -->
						{% if user.is_authenticated %}
							<li><a href=" {% url 'logout' %} ">Logout</a></li>
						{% else %}
							<li><a href=" {% url 'login' %} ">Login</a></li>
						{% endif %}
					</ul>
				</nav>

			<!-- Banner -->
				<section id="banner">
					<div class="content">
						<h2>Welcome to TXT by HTML5 UP</h2>
						<p>A free responsive site template built on HTML5, CSS3, and some other stuff</p>
						<a href=" {% static '#main' %} " class="button scrolly">Alright let's go</a>
					</div>
				</section>

			<!-- Main -->
				<section id="main">
					<div class="container">
						<div class="row gtr-200">
							<div class="col-12">

								<!-- Highlight -->
									<section class="box highlight">
										<ul class="special">
											<li><a href="#" class="icon solid fa-search"><span class="label">Magnifier</span></a></li>
											<li><a href="#" class="icon solid fa-tablet-alt"><span class="label">Tablet</span></a></li>
											<li><a href="#" class="icon solid fa-flask"><span class="label">Flask</span></a></li>
											<li><a href="#" class="icon solid fa-cog"><span class="label">Cog?</span></a></li>
										</ul>
										<header>
											<h2>A random assortment of icons in circles</h2>
											<p>And some text that attempts to explain their significance</p>
										</header>
										<p>
											Phasellus quam turpis, feugiat sit amet ornare in, hendrerit in lectus. Praesent semper mod quis eget mi. Etiam eu<br />
											ante risus. Aliquam erat volutpat. Aliquam luctus et mattis lectus amet pulvinar. Nam nec turpis consequat.
										</p>
									</section>

							</div>
							<div class="col-12">

								<!-- Features -->
									<section class="box features">
										<h2 class="major"><span>A Major Heading</span></h2>
										<div>
											<div class="row">
												<div class="col-3 col-6-medium col-12-small">

													<!-- Feature -->
														<section class="box feature">
															<a href="#" class="image featured"><img src=" {% static 'images/pic01.jpg' %} " alt="" /></a>
															<h3><a href="#">A Subheading</a></h3>
															<p>
																Phasellus quam turpis, feugiat sit amet ornare in, a hendrerit in
																lectus dolore. Praesent semper mod quis eget sed etiam eu ante risus.
															</p>
														</section>

												</div>
												<div class="col-3 col-6-medium col-12-small">

													<!-- Feature -->
														<section class="box feature">
															<a href="#" class="image featured"><img src=" {% static 'images/pic02.jpg' %} " alt="" /></a>
															<h3><a href="#">Another Subheading</a></h3>
															<p>
																Phasellus quam turpis, feugiat sit amet ornare in, a hendrerit in
																lectus dolore. Praesent semper mod quis eget sed etiam eu ante risus.
															</p>
														</section>

												</div>
												<div class="col-3 col-6-medium col-12-small">

													<!-- Feature -->
														<section class="box feature">
															<a href="#" class="image featured"><img src=" {% static 'images/pic03.jpg' %} " alt="" /></a>
															<h3><a href="#">And Another</a></h3>
															<p>
																Phasellus quam turpis, feugiat sit amet ornare in, a hendrerit in
																lectus dolore. Praesent semper mod quis eget sed etiam eu ante risus.
															</p>
														</section>

												</div>
												<div class="col-3 col-6-medium col-12-small">

													<!-- Feature -->
														<section class="box feature">
															<a href="#" class="image featured"><img src=" {% static 'images/pic04.jpg' %} " alt="" /></a>
															<h3><a href="#">And One More</a></h3>
															<p>
																Phasellus quam turpis, feugiat sit amet ornare in, a hendrerit in
																lectus dolore. Praesent semper mod quis eget sed etiam eu ante risus.
															</p>
														</section>

												</div>
												<div class="col-12">
													<ul class="actions">
														<li><a href="#" class="button large">Do Something</a></li>
														<li><a href="#" class="button alt large">Think About It</a></li>
													</ul>
												</div>
											</div>
										</div>
									</section>

							</div>
							<div class="col-12">

								<!-- Blog -->
									<section class="box blog">
										<h2 class="major"><span>Another Major Heading</span></h2>
										<div>
											<div class="row">
												<div class="col-9 col-12-medium">
													<div class="content">

														<!-- Featured Post -->
															<article class="box post">
																<header>
																	<h3><a href="#">Here's a really big heading</a></h3>
																	<p>With a smaller subtitle that attempts to elaborate</p>
																	<ul class="meta">
																		<li class="icon fa-clock">15 minutes ago</li>
																		<li class="icon fa-comments"><a href="#">8</a></li>
																	</ul>
																</header>
																<a href="#" class="image featured"><img src=" {% static 'images/pic05.jpg' %} " alt="" /></a>
																<p>
																	Phasellus quam turpis, feugiat sit amet ornare in, a hendrerit in lectus. Praesent
																	semper mod quis eget mi. Etiam sed ante risus aliquam erat et volutpat. Praesent a
																	dapibus velit. Curabitur sed nisi nunc, accumsan vestibulum lectus. Lorem ipsum
																	dolor sit non aliquet sed, tempor et dolor. Praesent a dapibus velit. Curabitur
																	accumsan.
																</p>
																<a href="#" class="button">Continue Reading</a>
															</article>

													</div>
												</div>
												<div class="col-3 col-12-medium">
													<div class="sidebar">

														<!-- Archives -->
															<ul class="divided">
																<li>
																	<article class="box post-summary">
																		<h3><a href="#">A Subheading</a></h3>
																		<ul class="meta">
																			<li class="icon fa-clock">6 hours ago</li>
																			<li class="icon fa-comments"><a href="#">34</a></li>
																		</ul>
																	</article>
																</li>
																<li>
																	<article class="box post-summary">
																		<h3><a href="#">Another Subheading</a></h3>
																		<ul class="meta">
																			<li class="icon fa-clock">9 hours ago</li>
																			<li class="icon fa-comments"><a href="#">27</a></li>
																		</ul>
																	</article>
																</li>
																<li>
																	<article class="box post-summary">
																		<h3><a href="#">And Another</a></h3>
																		<ul class="meta">
																			<li class="icon fa-clock">Yesterday</li>
																			<li class="icon fa-comments"><a href="#">184</a></li>
																		</ul>
																	</article>
																</li>
																<li>
																	<article class="box post-summary">
																		<h3><a href="#">And Another</a></h3>
																		<ul class="meta">
																			<li class="icon fa-clock">2 days ago</li>
																			<li class="icon fa-comments"><a href="#">286</a></li>
																		</ul>
																	</article>
																</li>
																<li>
																	<article class="box post-summary">
																		<h3><a href="#">And One More</a></h3>
																		<ul class="meta">
																			<li class="icon fa-clock">3 days ago</li>
																			<li class="icon fa-comments"><a href="#">8,086</a></li>
																		</ul>
																	</article>
																</li>
															</ul>
															<a href="#" class="button alt">Archives</a>

													</div>
												</div>
											</div>
										</div>
									</section>

							</div>
						</div>
					</div>
				</section>

			<!-- Footer -->
				<footer id="footer">
					<div class="container">
						<div class="row gtr-200">
							<div class="col-12">

								<!-- About -->
									<section>
										<h2 class="major"><span>What's this about?</span></h2>
										<p>
											This is <strong>TXT</strong>, yet another free responsive site template designed by
											<a href="http://twitter.com/ajlkn">AJ</a> for <a href="http://html5up.net">HTML5 UP</a>. It's released under the
											<a href="http://html5up.net/license/">Creative Commons Attribution</a> license so feel free to use it for
											whatever you're working on (personal or commercial), just be sure to give us credit for the design.
											That's basically it :)
										</p>
									</section>

							</div>
							<div class="col-12">

								<!-- Contact -->
									<section>
										<h2 class="major"><span>Get in touch</span></h2>
										<ul class="contact">
											<li><a class="icon brands fa-facebook-f" href="#"><span class="label">Facebook</span></a></li>
											<li><a class="icon brands fa-twitter" href="#"><span class="label">Twitter</span></a></li>
											<li><a class="icon brands fa-instagram" href="#"><span class="label">Instagram</span></a></li>
											<li><a class="icon brands fa-dribbble" href="#"><span class="label">Dribbble</span></a></li>
											<li><a class="icon brands fa-linkedin-in" href="#"><span class="label">LinkedIn</span></a></li>
										</ul>
									</section>

							</div>
						</div>

						<!-- Copyright -->
							<div id="copyright">
								<ul class="menu">
									<li>&copy; Untitled. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
								</ul>
							</div>

					</div>
				</footer>

		</div>

		<!-- Scripts -->
			<script src=" {% static 'assets/js/jquery.min.js' %} "></script>
			<script src=" {% static 'assets/js/jquery.dropotron.min.js' %} "></script>
			<script src=" {% static 'assets/js/jquery.scrolly.min.js' %} "></script>
			<script src=" {% static 'assets/js/browser.min.js' %} "></script>
			<script src=" {% static 'assets/js/breakpoints.min.js' %} "></script>
			<script src=" {% static 'assets/js/util.js' %} "></script>
			<script src=" {% static 'assets/js/main.js' %} "></script>

	</body>
</html>

main/templates/main/index.html
{% load static %}

<!DOCTYPE HTML>
<!--
	TXT by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Nirmaan Database</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href=" {% static 'assets/css/main.css' %} " />
	</head>
	<body class="homepage is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header">
					<div class="logo container">
						<div>
							<h1><a href="/" id="logo">Nirmaan</a></h1>
							<p>Towards a Better Future</p>
						</div>
					</div>
				</header>

			<!-- Nav -->
				<nav id="nav">
					<ul>
						<li class="current"><a href="/">Home</a></li>
						{% if user.is_authenticated %}
							<li>
								<a href="#">Contacts</a>
								<ul>
									<li><a href="{% url 'main:contact-table' %}">View All</a></li>
									<li><a href="{% url 'main:contact-create' %}">Create New</a></li>
									
								</ul>
							</li>
						{% endif %}
						<!-- <li><a href=" {% static 'left-sidebar.html' %} ">Left Sidebar</a></li>
						<li><a href=" {% static 'right-sidebar.html' %} ">Right Sidebar</a></li> -->
						{% if user.is_authenticated %}
							<li><a href=" {% url 'logout' %} ">Logout</a></li>
						{% else %}
							<li><a href=" {% url 'login' %} ">Login</a></li>
						{% endif %}
					</ul>
				</nav>

			

				<section id="main">
					<div class="container">
						<div class="row gtr-200">
							<div class="col-12">

								<!-- Highlight -->
									<section class="box highlight">
										<ul class="special">
											<li><a href="#" class="icon solid fa-handshake"><span class="label">Magnifier</span></a></li>
											<li><a href="#" class="icon solid fa-hand-holding-heart"><span class="label">Tablet</span></a></li>
											<li><a href="#" class="icon solid fa-seedling"><span class="label">Flask</span></a></li>
											<li><a href="#" class="icon solid fa-dove"><span class="label">Cog?</span></a></li>
										</ul>
										<header>
											<h2>We are Nirmaan</h2>
											<p>We have only one passion, the rise of a great nation</p>
										</header>
										<p>
											This is the database site for our partners and contacts
										</p>
									</section>
							</div>
						</div>
					</div>
				</section>

			<!-- Footer -->
			<footer id="footer">
				<div class="container">
					<div class="row gtr-200">
						<div id="copyright">
							<ul class="menu">
								<li>Made with &hearts; by Nirmaan PRD</li>
							</ul>
						</div>
					</div>
				</div>
			</footer>

		</div>

		<!-- Scripts -->
			<script src=" {% static 'assets/js/jquery.min.js' %} "></script>
			<script src=" {% static 'assets/js/jquery.dropotron.min.js' %} "></script>
			<script src=" {% static 'assets/js/jquery.scrolly.min.js' %} "></script>
			<script src=" {% static 'assets/js/browser.min.js' %} "></script>
			<script src=" {% static 'assets/js/breakpoints.min.js' %} "></script>
			<script src=" {% static 'assets/js/util.js' %} "></script>
			<script src=" {% static 'assets/js/main.js' %} "></script>

	</body>
</html>

main/templates/main/table.html
{% extends "main/base.html" %}
{% block content %}
  <article class="media content-section">
    <!-- <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}"> -->
    <div class="media-body">
        <table id="table_id" class="display" border='2' align="center"  style="width:100%">

            <caption><i>Contacts</i></caption>
        
            <thead>
                <tr>
                    <th>Company</th>
                    <th>Person</th>
                    <th>Description</th>
                    <th>Email</th>
                    <th>Number</th>
                    <th>Status</th>
                    
                </tr>
            </thead>
            <tbody>
                
                {% for c in contacts %}
                    <tr>
                        <TD class="c3" align="center"><a href="{% url 'main:contact-detail' c.id%}">{{ c.company }}</TD>
                        <TD class="c3" align="center">{{ c.person }}</TD>
                        <TD class="c3" align="center">{{ c.desc }}</TD>
                        <TD class="c3" align="left">{{ c.email }}</TD>
                        <TD class="c3" align="center">{{ c.number }}</TD>
                        <TD class="c3" align="center" >{{ c.status }}</TD>
                    </tr>
                {% endfor %}        
            </tbody>
        </table>
    </div>
  </article>
{% endblock content %}

{% block js %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.css"/>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.js"></script>
  <script>
      $(document).ready( function () {
      $('#table_id').DataTable({

      dom: 'B<"clear">lfrtip',
      buttons: {
          name: 'primary',
          buttons: [ 'copy', 'csv', 'excel', 'pdf' ]

          }}
      );
  } );
  </script>
{% endblock %}

users/templates/users/login.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "main/base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}